services:
  strom-app:
    build: .
    container_name: strom-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data        
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
